# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskGlamera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskGlamera
  pod 'SDWebImage'
  pod 'Moya'
  pod 'PromiseKit'
  pod 'ReachabilitySwift', '~> 5.0'
  pod 'lottie-ios'
  pod 'Drops', :git => 'https://github.com/omaralbeik/Drops.git', :tag => '1.4.0'
  pod 'MOLH'
  pod 'BSImagePicker'
  pod 'SwiftMessages'
  pod 'lottie-ios'



  target 'TaskGlameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaskGlameraUITests' do
    # Pods for testing
  end

end
